In [1]:
from etl_mc import ejecutar_etl_mercado_cambiario

# Obtener los 2 DataFrames consolidados
df_tc, df_cambiario = ejecutar_etl_mercado_cambiario('data/Base_Op_Cam.xlsx')

In [2]:
df_tc.tail(35)

           Fecha    Banco  Monto_Mm_USD  TC_Monto_Mm_USD         TC
1405  2026-09-02      BSO      5.557011        69.033920  12.422851
1406  2026-09-02      BUN      0.244356         2.995235  12.257666
1407  2026-09-02      PCO      0.030329         0.359699  11.860000
1408  2026-09-02      PEF      0.500075         6.275895  12.549896
1409  2026-09-02  Sistema     59.084914       728.019189  12.321575
1410  2026-09-03      BCR      4.227290        52.374204  12.389545
1411  2026-09-03      BEC      0.550258         6.873233  12.490919
1412  2026-09-03      BFO      0.167599         2.041925  12.183418
1413  2026-09-03      BGA      9.561345       118.956029  12.441349
1414  2026-09-03      BIE      1.322930        16.617804  12.561364
1415  2026-09-03      BIS      9.636272       119.792800  12.431446
1416  2026-09-03      BME      2.546894        31.896126  12.523539
1417  2026-09-03      BNA      0.046518         0.566498  12.178003
1418  2026-09-03      BNB      4.251287        52.611229  12.375366
1419  2026-09-03      BPR      0.011869         0.142660  12.020000
1420  2026-09-03      BSO      3.004362        37.769139  12.571432
1421  2026-09-03      BUN      0.004439         0.046605  10.500000
1422  2026-09-03      PCO      0.001566         0.018662  11.920000
1423  2026-09-03      PEF      0.000002         0.000025  11.920518
1424  2026-09-03  Sistema     35.332631       439.706939  12.444783
1425  2026-09-04      BCR      4.459706        56.031755  12.564001
1426  2026-09-04      BEC      4.057379        51.081474  12.589771
1427  2026-09-04      BFO      0.819769        10.359743  12.637396
1428  2026-09-04      BGA     20.567034       259.501350  12.617344
1429  2026-09-04      BIE      1.553359        19.599818  12.617697
1430  2026-09-04      BIS      9.516222       119.202925  12.526286
1431  2026-09-04      BME     10.460837       131.710879  12.590854
1432  2026-09-04      BNA      0.061090         0.756473  12.382935
1433  2026-09-04      BNB      4.520051        56.256868  12.446069
1434  2026-09-04      BPR      0.019358         0.235203  12.150000
1435  2026-09-04      BSO      0.818573        10.316046  12.602478
1436  2026-09-04      BUN      0.033370         0.385733  11.559240
1437  2026-09-04      PCO      0.005030         0.060611  12.050000
1438  2026-09-04      PEF           NaN              NaN        NaN
1439  2026-09-04  Sistema     56.891780       715.498879  12.576490

In [3]:
df_cv_mon.head(35)

         Fecha    Banco Operacion  Monto_Mm_USD
0   2026-06-01      BCR    Compra      0.765067
1   2026-06-01      BCR     Venta      0.223202
2   2026-06-01      BEC    Compra      1.526739
3   2026-06-01      BEC     Venta      0.171139
4   2026-06-01      BFO    Compra      0.152674
5   2026-06-01      BFO     Venta      0.101884
6   2026-06-01      BGA    Compra      3.864757
7   2026-06-01      BGA     Venta     12.259832
8   2026-06-01      BIE    Compra      0.185251
9   2026-06-01      BIE     Venta      0.452678
10  2026-06-01      BIS    Compra      3.344915
11  2026-06-01      BIS     Venta      6.477671
12  2026-06-01      BME    Compra      6.453115
13  2026-06-01      BME     Venta      1.176981
14  2026-06-01      BNA    Compra      0.024912
15  2026-06-01      BNA     Venta      0.108900
16  2026-06-01      BNB    Compra      4.027871
17  2026-06-01      BNB     Venta      2.512947
18  2026-06-01      BPR    Compra      0.013961
19  2026-06-01      BPR     Venta      0.000852
20  2026-06-01      BSO    Compra      1.064425
21  2026-06-01      BSO     Venta      0.578870
22  2026-06-01      BUN    Compra      0.143498
23  2026-06-01      BUN     Venta      0.196711
24  2026-06-01      PCO    Compra      0.000013
25  2026-06-01      PCO     Venta      0.005511
26  2026-06-01      PEF    Compra      0.000049
27  2026-06-01      PEF     Venta           NaN
28  2026-06-01  Sistema    Compra     21.567246
29  2026-06-01  Sistema     Venta     24.267177
30  2026-06-02      BCR    Compra      0.499793
31  2026-06-02      BCR     Venta      0.042163
32  2026-06-02      BEC    Compra      2.047425
33  2026-06-02      BEC     Venta      1.837274
34  2026-06-02      BFO    Compra      0.042948

In [4]:
df_cv_nop.head(35)

         Fecha    Banco Operacion  Numero_Operaciones
0   2026-06-01      BCR    Compra                  94
1   2026-06-01      BCR     Venta                  51
2   2026-06-01      BEC    Compra                  22
3   2026-06-01      BEC     Venta                3461
4   2026-06-01      BFO    Compra                  11
5   2026-06-01      BFO     Venta                   7
6   2026-06-01      BGA    Compra                 927
7   2026-06-01      BGA     Venta                3599
8   2026-06-01      BIE    Compra                  19
9   2026-06-01      BIE     Venta                 727
10  2026-06-01      BIS    Compra                 976
11  2026-06-01      BIS     Venta                2273
12  2026-06-01      BME    Compra                 175
13  2026-06-01      BME     Venta                5842
14  2026-06-01      BNA    Compra                  41
15  2026-06-01      BNA     Venta                   2
16  2026-06-01      BNB    Compra                 256
17  2026-06-01      BNB     Venta                7734
18  2026-06-01      BPR    Compra                  10
19  2026-06-01      BPR     Venta                  13
20  2026-06-01      BSO    Compra                  32
21  2026-06-01      BSO     Venta                 610
22  2026-06-01      BUN    Compra                  75
23  2026-06-01      BUN     Venta                7669
24  2026-06-01      PCO    Compra                   2
25  2026-06-01      PCO     Venta                   5
26  2026-06-01      PEF    Compra                   1
27  2026-06-01      PEF     Venta                <NA>
28  2026-06-01  Sistema    Compra                2641
29  2026-06-01  Sistema     Venta               31993
30  2026-06-02      BCR    Compra                  84
31  2026-06-02      BCR     Venta                  50
32  2026-06-02      BEC    Compra                  22
33  2026-06-02      BEC     Venta                3185
34  2026-06-02      BFO    Compra                   2

In [3]:
# Muestra de las primeras filas con Monto y Número de Operaciones juntos
df_cambiario.tail(50)

,Fecha,Banco,Operacion,Monto_Mm_USD,Numero_Operaciones,Monto_por_Op_USD
2830,2026-09-03,BIS,Compra,9.636272,165,58401.649205
2831,2026-09-03,BIS,Venta,25.576801,2095,12208.496878
2832,2026-09-03,BME,Compra,2.546894,343,7425.347023
2833,2026-09-03,BME,Venta,3.719346,6321,588.410951
2834,2026-09-03,BNA,Compra,0.046518,35,1329.088569
2835,2026-09-03,BNA,Venta,0.153936,8,19242.039987
2836,2026-09-03,BNB,Compra,4.251287,442,9618.295609
2837,2026-09-03,BNB,Venta,3.448285,11477,300.451745
2838,2026-09-03,BPR,Compra,0.011869,22,539.480905
2839,2026-09-03,BPR,Venta,0.005263,8,657.9375
2840,2026-09-03,BSO,Compra,3.004362,55,54624.771447
2841,2026-09-03,BSO,Venta,0.832775,1033,806.171132
2842,2026-09-03,BUN,Compra,0.004439,47,94.438294
2843,2026-09-03,BUN,Venta,1.329849,5245,253.546126
2844,2026-09-03,PCO,Compra,0.001566,7,223.66
2845,2026-09-03,PCO,Venta,0.001177,6,196.191667
2846,2026-09-03,PEF,Compra,0.000002,3,0.7033
2847,2026-09-03,PEF,Venta,NaN,<NA>,<NA>
2848,2026-09-03,Sistema,Compra,35.332631,2473,14287.355788
2849,2026-09-03,Sistema,Venta,45.016536,39068,1152.261083
2850,2026-09-04,BCR,Compra,4.459706,522,8543.49862
2851,2026-09-04,BCR,Venta,4.147814,50,82956.277198
2852,2026-09-04,BEC,Compra,4.057379,60,67622.983328
2853,2026-09-04,BEC,Venta,1.058155,3535,299.336747
2854,2026-09-04,BFO,Compra,0.819769,12,68314.067483
2855,2026-09-04,BFO,Venta,0.113348,13,8719.057685
2856,2026-09-04,BGA,Compra,20.567034,281,73192.292558
2857,2026-09-04,BGA,Venta,0.035194,1357,25.935438
2858,2026-09-04,BIE,Compra,1.553359,30,51778.647333
2859,2026-09-04,BIE,Venta,0.950452,445,2135.847011
2860,2026-09-04,BIS,Compra,9.516222,114,83475.633061
2861,2026-09-04,BIS,Venta,5.808681,2229,2605.958389
2862,2026-09-04,BME,Compra,10.460837,359,29138.822867
2863,2026-09-04,BME,Venta,1.621809,4053,400.150182
2864,2026-09-04,BNA,Compra,0.061090,19,3215.259474
2865,2026-09-04,BNA,Venta,0.035956,5,7191.1
2866,2026-09-04,BNB,Compra,4.520051,467,9678.910661
2867,2026-09-04,BNB,Venta,0.450534,7005,64.316039
2868,2026-09-04,BPR,Compra,0.019358,17,1138.720582
2869,2026-09-04,BPR,Venta,0.000495,7,70.704286
2870,2026-09-04,BSO,Compra,0.818573,49,16705.568365
2871,2026-09-04,BSO,Venta,0.389666,652,597.647898
2872,2026-09-04,BUN,Compra,0.033370,42,794.525471
2873,2026-09-04,BUN,Venta,0.127623,5419,23.550935
2874,2026-09-04,PCO,Compra,0.005030,2,2515.0
2875,2026-09-04,PCO,Venta,0.003436,7,490.834286
2876,2026-09-04,PEF,Compra,NaN,<NA>,<NA>
2877,2026-09-04,PEF,Venta,0.000956,2,478.08495
2878,2026-09-04,Sistema,Compra,56.891780,1974,28820.557079
2879,2026-09-04,Sistema,Venta,14.744119,24779,595.024759

In [4]:
# 1. Cargar las funciones
from etl_mc import ejecutar_etl_mercado_cambiario
from indicadores_mc import (
    calcular_kpi_temporales_tc,
    calcular_kpi_temporales_cambiario,
    ranking_competitividad_diario,
    estructura_mercado_pareto,
    calcular_hhi_operaciones
)

# 2. Cargar datos
df_tc, df_cambiario = ejecutar_etl_mercado_cambiario('data/Base_Op_Cam.xlsx')

# 3. Probando KPI Temporales de TC
df_kpi_tc = calcular_kpi_temporales_tc(df_tc, entidad='Sistema')
df_kpi_tc.tail(10)

ImportError: cannot import name 'calcular_kpi_temporales_cambiario' from 'indicadores_mc' (C:\Users\sergio.garnica\Mercado Cambiario y Liquidez V2\indicadores_mc.py)

In [5]:
# 4. Probando Pareto y Cuotas de Mercado para una fecha específica (Compra)
df_pareto = estructura_mercado_pareto(df_cambiario, fecha_consulta='2026-08-04', operacion='Compra')
df_pareto

NameError: name 'estructura_mercado_pareto' is not defined

In [6]:
# 5. Probando el Índice Herfindahl (HHI) para N° de Operaciones
df_hhi_compra = calcular_hhi_operaciones(df_cambiario, operacion='Venta')
df_hhi_compra.tail(10)

NameError: name 'calcular_hhi_operaciones' is not defined

In [8]:
from etl_liq import ejecutar_etl_liquidez
from indicadores_liq import calcular_ratio_bym_pcpl

# 1. Ejecutar ETL
df_bym, df_pcpl = ejecutar_etl_liquidez('data/Base PCam.xlsx')

print("=== Pestaña 1: AP-ByM ===")
print(df_bym.info())
display(df_bym.head(10))

print("\n=== Pestaña 2: PCPL ===")
print(df_pcpl.info())
display(df_pcpl.head(10))

# 2. Calcular Ratio
df_ratio = calcular_ratio_bym_pcpl(df_bym, df_pcpl)

print("\n=== Indicador: Billetes y Monedas / Pasivos Corto Plazo (%) ===")
display(df_ratio[df_ratio['Moneda'] == 'Consolidado'].head(20))

=== Pestaña 1: AP-ByM ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162792 entries, 0 to 162791
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Fecha        162792 non-null  object
 1   Descripcion  162792 non-null  object
 2   Moneda       162792 non-null  object
 3   Banco        162792 non-null  object
 4   Monto_Mm_Bs  162792 non-null  float64
dtypes: float64(1), object(4)
memory usage: 6.2+ MB
None

        Fecha         Descripcion Moneda Banco   Monto_Mm_Bs
0  2024-01-01              ACTIVO     ME   BCR   2361.907074
1  2024-01-01              ACTIVO     MN   BCR  22762.301402
2  2024-01-01  Billetes y monedas     ME   BCR    261.259066
3  2024-01-01  Billetes y monedas     MN   BCR    605.848332
4  2024-01-01    DISPONIBILIDADES     ME   BCR    715.654108
5  2024-01-01    DISPONIBILIDADES     MN   BCR   2816.883856
6  2024-01-01              PASIVO     ME   BCR   1711.021288
7  2024-01-01              PASIVO     MN   BCR  21705.929595
8  2024-01-02              ACTIVO     ME   BCR   2341.326614
9  2024-01-02              ACTIVO     MN   BCR  22738.796840

=== Pestaña 2: PCPL ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40698 entries, 0 to 40697
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        40698 non-null  object
 1   Descripcion  40698 non-null  object
 2   Moneda       40698 non-null  object
 3   Banco        40698 non-null  object
 4   Monto_Mm_Bs  40698 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.6+ MB
None

        Fecha              Descripcion Moneda Banco   Monto_Mm_Bs
0  2024-01-01  . Pasivo de corto plazo     ME   BCR   1522.858811
1  2024-01-01  . Pasivo de corto plazo     MN   BCR   9988.410357
2  2024-01-02  . Pasivo de corto plazo     ME   BCR   1522.529498
3  2024-01-02  . Pasivo de corto plazo     MN   BCR  10020.586567
4  2024-01-03  . Pasivo de corto plazo     ME   BCR   1521.153241
5  2024-01-03  . Pasivo de corto plazo     MN   BCR   9972.580020
6  2024-01-04  . Pasivo de corto plazo     ME   BCR   1523.076182
7  2024-01-04  . Pasivo de corto plazo     MN   BCR   9994.933388
8  2024-01-05  . Pasivo de corto plazo     ME   BCR   1512.884838
9  2024-01-05  . Pasivo de corto plazo     MN   BCR  10028.258195

=== Indicador: Billetes y Monedas / Pasivos Corto Plazo (%) ===

C:\Users\sergio.garnica\Mercado Cambiario y Liquidez V2\indicadores_liq.py:21: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_ratio['Ratio_ByM_PCPL_%'] = df_ratio['Ratio_ByM_PCPL_%'].fillna(0)

,Fecha,Banco,Moneda,ByM_Mm_Bs,Pasivos_CPL_Mm_Bs,Ratio_ByM_PCPL_%,Fecha_dt
1938,2024-01-01,BCR,Consolidado,867.107398,11511.269168,7.532683,2024-01-01
4845,2024-01-01,BEC,Consolidado,547.002626,4234.776244,12.916919,2024-01-01
7752,2024-01-01,BFO,Consolidado,85.267352,1631.999159,5.224718,2024-01-01
10659,2024-01-01,BGA,Consolidado,595.519507,7729.580309,7.704422,2024-01-01
13566,2024-01-01,BIE,Consolidado,491.151141,7979.897206,6.154855,2024-01-01
16473,2024-01-01,BIS,Consolidado,852.203565,11631.753477,7.326527,2024-01-01
19380,2024-01-01,BME,Consolidado,1332.011291,19138.391653,6.959891,2024-01-01
22287,2024-01-01,BNB,Consolidado,1113.706182,14908.245732,7.470404,2024-01-01
25194,2024-01-01,BPR,Consolidado,223.287593,2252.819488,9.911473,2024-01-01
28101,2024-01-01,BSO,Consolidado,577.152543,8228.762332,7.013844,2024-01-01
31008,2024-01-01,BUN,Consolidado,1673.820316,27761.023480,6.029390,2024-01-01
33915,2024-01-01,PCO,Consolidado,21.670921,320.671747,6.757976,2024-01-01
36822,2024-01-01,PEF,Consolidado,126.608012,1464.025131,8.647940,2024-01-01
39729,2024-01-01,Sistema,Consolidado,8506.508448,118793.215126,7.160770,2024-01-01
1939,2024-01-02,BCR,Consolidado,850.794767,11543.116065,7.370581,2024-01-02
4846,2024-01-02,BEC,Consolidado,561.664422,4236.676826,13.257193,2024-01-02
7753,2024-01-02,BFO,Consolidado,83.163405,1576.809282,5.274158,2024-01-02
10660,2024-01-02,BGA,Consolidado,638.551344,7838.482046,8.146365,2024-01-02
13567,2024-01-02,BIE,Consolidado,509.366119,8012.283272,6.357315,2024-01-02
16474,2024-01-02,BIS,Consolidado,888.740232,11615.969666,7.651021,2024-01-02

In [9]:
import sys

print("Versión de Python:", sys.version)
print("Ejecutable:", sys.executable)

Versión de Python: 3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]
Ejecutable: C:\ProgramData\anaconda3\python.exe